#!/usr/bin/env python3
"""Generate firmware/secrets_config.py from the PLAINTEXT answer table.

This file is the single source of truth for the hidden-channel table and
lives in sitegen/ (NEVER deployed, NEVER copied to the device). The
generated secrets_config.py ships on the CIRCUITPY drive and contains only
FNV-1a hashes of the channel strings, so mounting the drive and reading
the source no longer spoils the game (both expert-tier
testers did exactly that). Reward GIF paths remain visible — filenames
hint themes, not numbers. Regenerate + verify:

    python3 sitegen/gen_secrets.py
    python3 -m py_compile firmware/secrets_config.py
"""
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "firmware" / "secrets_config.py"


def fnv(s, salt=""):
    x = 0x811C9DC5
    for c in (salt + s).encode():
        x = ((x ^ c) * 0x01000193) & 0xFFFFFFFF
    return "%08x" % x


# --- PLAINTEXT TABLES (answers!) -------------------------------------------
FREQS = {  # channel -> (gif, case comment for THIS file only)
    # NOTE: reward filenames may hint THEMES but never contain answer
    # digits — the /secret directory listing is visible to anyone who
    # mounts the drive (hence ident.gif not ident341.gif, silicon.gif
    # not chip4004.gif).
    "034.1": ("/secret/ident.gif",       "CF-00 Sign-On"),
    "199.3": ("/secret/defcon1.gif",     "CF-01 First Transmission"),
    "080.0": ("/secret/gadget.gif",      "CF-02 Know Your Set"),
    "400.4": ("/secret/silicon.gif",     "CF-03 Count the Frames"),
    "170.4": ("/secret/wopr.gif",        "CF-04 Only Winning Move"),
    "011.0": ("/secret/maxheadroom.gif", "CF-05 Signal Intrusion"),
    "023.0": ("/secret/testcardf.gif",   "CF-06 Test Card Lineage (knock)"),
    "066.0": ("/secret/apollo.gif",      "CF-07 Tranquility Descent (knock)"),
    "404.0": ("/secret/meeseeks.gif",    "CF-09 Master Control (meta)"),
    # insider channels: know-the-reference internet lore
    "053.0": ("/secret/dns.gif",         "insider"),
    "088.0": ("/secret/keyboardcat.gif", "insider"),
    "210.1": ("/secret/allyourbase.gif", "insider"),
    "911.0": ("/secret/this_is_fine.gif", "insider"),
    "222.0": ("/secret/nyan.gif",        "insider"),
    "123.0": ("/secret/elmothunder.gif", "insider"),  # 123 Sesame St (123.4 is a trap; the .0 pays off)
    # software-culture channels: hidden per the maker's rule — the visible
    # dial is TV/movies/commercials/music video ONLY (Jul 22)
    "098.0": ("/secret/bsod.gif",        "insider"),  # Windows 98
    "097.0": ("/secret/clippy.gif",      "insider"),  # Office 97
    "089.0": ("/secret/toasters.gif",    "insider"),  # After Dark, 1989
}

TRAP_FREQS = {  # play once, never persist; none collide with FREQS
    "067.0": "/secret/nogod67.gif",
    "420.0": "/secret/weed420.gif",
    "187.0": "/secret/spyvsspy.gif",
    "013.3": "/secret/dickbutt.gif",
    "069.0": "/secret/rickroll.gif",
    "042.0": "/secret/dontpanic.gif",   # dead CH 42 pays off as designed
    "007.0": "/secret/rickroll.gif",
    "123.4": "/secret/rickroll.gif",
    "088.8": "/secret/rickroll.gif",
    "000.0": "/secret/rickroll.gif",
    "666.0": "/secret/rickroll.gif",
    "133.7": "/secret/rickroll.gif",
    "777.0": "/secret/jackpot777.gif", # the most Vegas number gets a jackpot
    # playtest additions: the two most-dialed wrong answers
    "345.0": "/secret/paperwork.gif",  # CF-02's form number, dialed hopefully
    "009.0": "/secret/movedon.gif",    # CF-05: the intruder hit ch 9 first
}

# Station-knock sequences (ordered). Steps use the same NNN.N namespace as
# the dial: a SURF visit to integer channel n counts as "0NN.0", a DIALED
# frequency counts as itself. Final step doubles as a plain FREQS unlock.
KNOCKS = [
    ("003.0", "006.0", "023.0"),   # CF-06: cards C, F, W by alphabet seat
    ("063.0", "064.0", "066.0"),   # CF-07: P63 -> P64 -> P66, the descent
]

# ---------------------------------------------------------------------------
# Pick a salt whose entire hash set contains no answer-digit run — even a
# coincidental "341" inside a hex hash would look like a breadcrumb.
BAD = ["0341", "1993", "0800", "4004", "1704", "0110", "0230", "0660",
       "4040", "341"] + [c for c in FREQS] + [c for c in TRAP_FREQS]
ALL = sorted(set(FREQS) | set(TRAP_FREQS)
             | {s for seq in KNOCKS for s in seq})
SALT = None
for n in range(10000):
    cand = "IN34/%d:" % n
    hashes = [fnv(c, cand) for c in ALL]
    if (len(set(hashes)) == len(ALL)
            and not any(b in h for h in hashes for b in BAD)):
        SALT = cand
        break
if SALT is None:
    raise SystemExit("no clean salt found")


def fnvs(s):
    return fnv(s, SALT)


lines = [
    "# DC34 Meme TV SAO -- hidden channel table (\"TUNE YOUR OWN SIGNAL\")",
    "# Consumed by tuner.py. GENERATED by sitegen/gen_secrets.py -- edit the",
    "# plaintext table there, never this file.",
    "#",
    "# Keys are FNV-1a hashes of the channel string, so reading this file",
    "# off the CIRCUITPY drive tells you nothing about what to dial. The",
    "# rewards are earned, operator. TUNE YOUR OWN SIGNAL.",
    "#",
    "# NVM slot = index in the sorted hash list; regenerating with a changed",
    "# table renumbers slots -- bump tuner.VERSION if that happens after",
    "# boards ship.",
    "",
    'SALT = "%s"' % SALT,
    "",
    "FREQS = {",
]
# emit in HASH order, not channel order — a channel-sorted dict is a
# pencil-and-paper cryptogram (ascending order + theme filenames)
for ch in sorted(FREQS, key=fnvs):
    gif, _case = FREQS[ch]
    lines.append('    "%s": "%s",' % (fnvs(ch), gif))
lines += [
    "}",
    "",
    "# KONAMI easter egg: enter this button sequence during normal playback.",
    "# Reward = Mooncake, a callback to the maker's DC26 SAO.",
    'KONAMI = ("up", "up", "down", "down", "up", "down", "mode")',
    'KONAMI_GIF = "/secret/mooncake.gif"',
    "",
    "# Field Contact: auto-unlocks the first time a live badge (any I2C",
    "# master) talks to us at the SAO address. The handshake is the license.",
    'BADGE_GIF = "/secret/badgelink.gif"',
    "",
    "# TRAPS + JOKE NUMBERS: dialing one plays the GIF ONCE (a gotcha) --",
    "# it does NOT persist and never joins the rotation.",
    "TRAP_FREQS = {",
]
for ch in sorted(TRAP_FREQS, key=fnvs):
    lines.append('    "%s": "%s",' % (fnvs(ch), TRAP_FREQS[ch]))
lines += [
    "}",
    "",
    "# STATION KNOCK sequences: ordered step hashes; the set acknowledges",
    "# each correct step (CARRIER HELD) and grants the license on the last.",
    "KNOCKS = (",
]
for seq in KNOCKS:
    lines.append("    (%s)," % ", ".join('"%s"' % fnvs(s) for s in seq))
lines += [")", ""]

OUT.write_text("\n".join(lines))
print("wrote", OUT)

# Freeze guardrail (build-time). On-device unlock flags are indexed by the
# SORTED hash order. If this table (FREQS content or SALT) changes AFTER any
# board is flashed and tuner.VERSION is NOT bumped, the NVM header still
# matches and old flag bits map to DIFFERENT channels — persisted unlocks
# silently point at the wrong secret. There is no runtime check, so this
# prints a fingerprint of the sorted hashes: if it differs from what a
# flashed board carries, bump tuner.VERSION. (Recommended follow-up: fold
# this fingerprint into the NVM header to auto-invalidate — needs hardware
# validation first.)
_fp = 0
for _h in sorted(fnvs(c) for c in FREQS):
    for _ch in str(_h):
        _fp = ((_fp * 31) + ord(_ch)) & 0xFFFF
print("channel-table fingerprint: %04X" % _fp)
print("!! If a board was flashed with a DIFFERENT fingerprint, bump "
      "tuner.VERSION (see CASES.md / HANDOFF) so unlock progress re-aligns.")

# --- CHANNELS.md: the full channel roster (ANSWERS — sitegen/ only) --------
import ast, re
_code = (Path(__file__).resolve().parents[1] / "firmware" / "code.py").read_text()
_cm = ast.literal_eval("{" + re.search(r"CHANNEL_MAP = \{(.*?)\}", _code, re.S).group(1) + "}")
_sn = ast.literal_eval("{" + re.search(r"SHOW_NAMES = \{(.*?)\}", _code, re.S).group(1) + "}")
_dead = ast.literal_eval(re.search(r"DEAD_CHANNELS = (\([^)]*\))", _code).group(1))
_root = Path(__file__).resolve().parents[1]

def _kb(rel):
    f = _root / rel.lstrip("/")
    return "%dKB" % (f.stat().st_size // 1024) if f.exists() else "MISSING"

r = ["# CHANNEL ROSTER — GENERATED by gen_secrets.py, do not hand-edit.",
     "# Contains ALL ANSWERS. sitegen/ only — never deploy, never copy to",
     "# the device. Regenerate: python3 sitegen/gen_secrets.py", "",
     "## Visible dial (%d channels — TV/movies/commercials/music video only)" % len(_cm), "",
     "| CH | file | shown as | size |", "|---|---|---|---|"]
for base, ch in sorted(_cm.items(), key=lambda kv: kv[1]):
    r.append("| %d | memes/%s.gif | %s | %s |" % (ch, base, _sn.get(base, base.upper()), _kb("memes/%s.gif" % base)))
r += ["", "## Dead air (knock seats; prune when their reward unlocks)", "",
      ", ".join("CH %d" % d for d in _dead), "",
      "## Hidden — dial to unlock (%d)" % len(FREQS), "",
      "| dial | file | note | size |", "|---|---|---|---|"]
for ch in sorted(FREQS):
    gif, note = FREQS[ch]
    r.append("| %s | %s | %s | %s |" % (ch, gif, note, _kb(gif)))
r += ["", "## Station knocks", ""]
for seq in KNOCKS:
    r.append("- " + " -> ".join(seq))
r += ["", "## Other unlocks", "",
      "- Konami (up up down down up down MODE) -> /secret/mooncake.gif (%s)" % _kb("secret/mooncake.gif"),
      "- Badge I2C first contact -> /secret/badgelink.gif (%s)" % _kb("secret/badgelink.gif"), "",
      "## Traps (play once, never persist)", "",
      "| dial | file |", "|---|---|"]
for ch in sorted(TRAP_FREQS):
    r.append("| %s | %s |" % (ch, TRAP_FREQS[ch]))
(_root / "sitegen" / "CHANNELS.md").write_text("\n".join(r) + "\n")
print("wrote", _root / "sitegen" / "CHANNELS.md")
for ch in sorted(FREQS, key=fnvs):
    print(" ", fnvs(ch), "<-", ch, FREQS[ch][1])
