# DC34 Meme TV SAO -- hidden channel table ("TUNE YOUR OWN SIGNAL")
# Consumed by tuner.py. GENERATED by sitegen/gen_secrets.py -- edit the
# plaintext table there, never this file.
#
# Keys are FNV-1a hashes of the channel string, so reading this file
# off the CIRCUITPY drive tells you nothing about what to dial. The
# rewards are earned, operator. TUNE YOUR OWN SIGNAL.
#
# NVM slot = index in the sorted hash list; regenerating with a changed
# table renumbers slots -- bump tuner.VERSION if that happens after
# boards ship.

SALT = "IN34/0:"

FREQS = {
    "0f2b90f8": "/secret/nyan.gif",
    "2c0b31ba": "/secret/gadget.gif",
    "354c58b2": "/secret/keyboardcat.gif",
    "5d015a4a": "/secret/ident.gif",
    "6782b16a": "/secret/silicon.gif",
    "73d0c52f": "/secret/this_is_fine.gif",
    "86c19ced": "/secret/testcardf.gif",
    "8db467f6": "/secret/apollo.gif",
    "8e43e3fa": "/secret/allyourbase.gif",
    "8e548bd2": "/secret/wopr.gif",
    "8ee199b2": "/secret/meeseeks.gif",
    "9b8aecd9": "/secret/toasters.gif",
    "a81641b2": "/secret/elmothunder.gif",
    "b6fe4d16": "/secret/clippy.gif",
    "b71279c6": "/secret/dns.gif",
    "ba4e35aa": "/secret/defcon1.gif",
    "c82b9f73": "/secret/bsod.gif",
    "e03995ec": "/secret/maxheadroom.gif",
}

# KONAMI easter egg: enter this button sequence during normal playback.
# Reward = Mooncake, a callback to the maker's DC26 SAO.
KONAMI = ("up", "up", "down", "down", "up", "down", "mode")
KONAMI_GIF = "/secret/mooncake.gif"

# Field Contact: auto-unlocks the first time a live badge (any I2C
# master) talks to us at the SAO address. The handshake is the license.
BADGE_GIF = "/secret/badgelink.gif"

# TRAPS + JOKE NUMBERS: dialing one plays the GIF ONCE (a gotcha) --
# it does NOT persist and never joins the rotation.
TRAP_FREQS = {
    "09d96a2f": "/secret/dickbutt.gif",
    "1185a03c": "/secret/weed420.gif",
    "1938074c": "/secret/paperwork.gif",
    "1ee0f0d3": "/secret/rickroll.gif",
    "3d4c654a": "/secret/rickroll.gif",
    "91d2bb81": "/secret/movedon.gif",
    "93f264fd": "/secret/nogod67.gif",
    "9ff6a8b2": "/secret/rickroll.gif",
    "a1ea2f3c": "/secret/rickroll.gif",
    "a4163b66": "/secret/rickroll.gif",
    "ab522671": "/secret/jackpot777.gif",
    "b2541ad8": "/secret/spyvsspy.gif",
    "b398e352": "/secret/rickroll.gif",
    "b62067a0": "/secret/dontpanic.gif",
    "c4c635af": "/secret/rickroll.gif",
}

# STATION KNOCK sequences: ordered step hashes; the set acknowledges
# each correct step (CARRIER HELD) and grants the license on the last.
KNOCKS = (
    ("f074d623", "5e87a188", "86c19ced"),
    ("bfa10571", "62c4e040", "8db467f6"),
)
